name: build-a-llm-from-scratch
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab >=4.0
  - tiktoken >=0.5.1
  - matplotlib >=3.7.1
  - tqdm >=4.66.1
  - numpy >=1.26
  - pandas >=2.2.1
  - psutil >=5.9.5
  - pytorch::pytorch
  - tensorflow